-- ===================================================================
-- Yozakura - night_blue palette
-- Auto-generated from lush theme - DO NOT EDIT MANUALLY
-- To regenerate: ./scripts/compile-lush.lua
-- ===================================================================

local M = {}

function M.setup()
  local highlights = {
    ["@tag.attribute.jsx"] = { fg = "#CFA5C8" },
    ["@tag.jsx"] = { fg = "#E1C1D6" },
    ["@tag.attribute.tsx"] = { fg = "#CFA5C8" },
    ["@tag.tsx"] = { fg = "#E1C1D6" },
    ["@tag.attribute.vue"] = { fg = "#CFA5C8" },
    ["@tag.vue"] = { fg = "#E1C1D6" },
    ["@tag.attribute.html"] = { fg = "#CFA5C8" },
    ["@tag.html"] = { fg = "#E1C1D6" },
    ["@type.css"] = { fg = "#78A0F7" },
    ["Include"] = { fg = "#BC9CF7" },
    ["Define"] = { fg = "#BC9CF7" },
    ["Macro"] = { fg = "#BC9CF7" },
    ["PreCondit"] = { fg = "#BC9CF7" },
    ["Type"] = { fg = "#78A0F7" },
    ["StorageClass"] = { fg = "#78A0F7" },
    ["Structure"] = { fg = "#78A0F7" },
    ["Typedef"] = { fg = "#78A0F7" },
    ["Special"] = { fg = "#E1C1D6" },
    ["SpecialChar"] = { fg = "#E1C1D6" },
    ["Tag"] = { fg = "#E1C1D6" },
    ["Delimiter"] = { fg = "#E0E0F0" },
    ["@punctuation.delimiter"] = { fg = "#E0E0F0" },
    ["SpecialComment"] = { fg = "#C190B8", italic = true },
    ["Debug"] = { fg = "#F7788F" },
    ["Underlined"] = { underline = true },
    ["@string.special.css"] = { fg = "#E1C1D6" },
    ["Ignore"] = { fg = "#6E7296" },
    ["Error"] = { fg = "#F7788F" },
    ["Todo"] = { fg = "#FF9E66", bold = true },
    ["@property.css"] = { fg = "#CFA5C8" },
    ["DiagnosticError"] = { fg = "#F7788F" },
    ["DiagnosticWarn"] = { fg = "#FF9E66" },
    ["DiagnosticInfo"] = { fg = "#78A0F7" },
    ["DiagnosticHint"] = { fg = "#72DACA" },
    ["GitSignsAdd"] = { fg = "#9DCE69" },
    ["GitSignsChange"] = { fg = "#FF9E66" },
    ["GitSignsDelete"] = { fg = "#F7788F" },
    ["@variable"] = { fg = "#9D88A5" },
    ["@variable.builtin"] = { fg = "#BC9CF7" },
    ["@variable.parameter"] = { fg = "#CFA5C8" },
    ["@variable.member"] = { fg = "#CFA5C8" },
    ["@constant"] = { fg = "#FF9E66" },
    ["@constant.builtin"] = { fg = "#FF9E66" },
    ["@constant.macro"] = { fg = "#FF9E66" },
    ["@string"] = { fg = "#E1C1D6" },
    ["@string.documentation"] = { fg = "#E1C1D6" },
    ["@string.regexp"] = { fg = "#F7788F" },
    ["@string.escape"] = { fg = "#CFA5C8" },
    ["@string.special"] = { fg = "#E1C1D6" },
    ["@string.special.symbol"] = { fg = "#FF9E66" },
    ["@string.special.url"] = { fg = "#78A0F7", underline = true },
    ["@character"] = { fg = "#E1C1D6" },
    ["@character.special"] = { fg = "#CFA5C8" },
    ["@number"] = { fg = "#F7CFE8" },
    ["@number.float"] = { fg = "#F7CFE8" },
    ["@boolean"] = { fg = "#C190B8" },
    ["@function"] = { fg = "#CFA5C8" },
    ["@function.builtin"] = { fg = "#CFA5C8" },
    ["@function.macro"] = { fg = "#CFA5C8" },
    ["@function.call"] = { fg = "#CFA5C8" },
    ["@function.method"] = { fg = "#78A0F7" },
    ["@method"] = { fg = "#78A0F7" },
    ["@function.method.call"] = { fg = "#78A0F7" },
    ["@method.call"] = { fg = "#78A0F7" },
    ["@constructor"] = { fg = "#CFA5C8" },
    ["@parameter"] = { fg = "#CFA5C8" },
    ["@parameter.reference"] = { fg = "#CFA5C8" },
    ["@keyword"] = { fg = "#C190B8" },
    ["@keyword.coroutine"] = { fg = "#C190B8" },
    ["@keyword.function"] = { fg = "#C190B8" },
    ["@keyword.operator"] = { fg = "#575B7F" },
    ["@keyword.import"] = { fg = "#BC9CF7" },
    ["@keyword.storage"] = { fg = "#C190B8" },
    ["@keyword.repeat"] = { fg = "#C190B8" },
    ["@keyword.return"] = { fg = "#78A0F7" },
    ["@keyword.debug"] = { fg = "#F7788F" },
    ["@keyword.exception"] = { fg = "#F7788F" },
    ["@conditional"] = { fg = "#C190B8" },
    ["@conditional.ternary"] = { fg = "#C190B8" },
    ["@repeat"] = { fg = "#C190B8" },
    ["@label"] = { fg = "#C190B8" },
    ["@exception"] = { fg = "#F7788F" },
    ["@type"] = { fg = "#CFA5C8" },
    ["@type.builtin"] = { fg = "#CFA5C8" },
    ["@type.definition"] = { fg = "#CFA5C8" },
    ["@type.qualifier"] = { fg = "#C190B8" },
    ["@interface"] = { fg = "#C190B8" },
    ["@attribute"] = { fg = "#BC9CF7" },
    ["@attribute.builtin"] = { fg = "#BC9CF7" },
    ["@field"] = { fg = "#CFA5C8" },
    ["@property"] = { fg = "#CFA5C8" },
    ["@namespace"] = { fg = "#78A0F7" },
    ["@namespace.builtin"] = { fg = "#78A0F7" },
    ["@module"] = { fg = "#BC9CF7" },
    ["@module.builtin"] = { fg = "#BC9CF7" },
    ["@include"] = { fg = "#BC9CF7" },
    ["@punctuation.bracket"] = { fg = "#E0E0F0" },
    ["@punctuation.special"] = { fg = "#E0E0F0" },
    ["@comment"] = { fg = "#6E7296", italic = true },
    ["@comment.documentation"] = { fg = "#6E7296", italic = true },
    ["@comment.error"] = { fg = "#F7788F", italic = true },
    ["@comment.warning"] = { fg = "#FF9E66", italic = true },
    ["@comment.todo"] = { fg = "#FF9E66", italic = true, bold = true },
    ["@property.toml"] = { fg = "#CFA5C8" },
    ["@comment.note"] = { fg = "#9DCE69", italic = true },
    ["@tag"] = { fg = "#E1C1D6" },
    ["@tag.builtin"] = { fg = "#E1C1D6" },
    ["@tag.attribute"] = { fg = "#CFA5C8" },
    ["@tag.delimiter"] = { fg = "#E0E0F0" },
    ["@markup"] = { fg = "#E1C1D6" },
    ["@markup.strong"] = { bold = true },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.strike"] = { strikethrough = true },
    ["@property.yaml"] = { fg = "#CFA5C8" },
    ["@markup.heading"] = { fg = "#CFA5C8", bold = true },
    ["@markup.quote"] = { fg = "#C190B8", italic = true },
    ["@markup.math"] = { fg = "#FF9E66" },
    ["@markup.environment"] = { fg = "#BC9CF7" },
    ["@markup.link"] = { fg = "#72DACA", underline = true },
    ["@markup.link.url"] = { fg = "#72DACA", underline = true },
    ["@markup.link.label"] = { fg = "#CFA5C8" },
    ["@markup.raw"] = { fg = "#72DACA" },
    ["@markup.raw.block"] = { fg = "#72DACA" },
    ["@markup.list"] = { fg = "#C190B8" },
    ["@markup.list.checked"] = { fg = "#9DCE69" },
    ["@markup.list.unchecked"] = { fg = "#C190B8" },
    ["@diff.plus"] = { fg = "#9DCE69" },
    ["@diff.minus"] = { fg = "#F7788F" },
    ["@diff.delta"] = { fg = "#FF9E66" },
    ["@lsp.type.method"] = { fg = "#78A0F7" },
    ["@lsp.type.property"] = { fg = "#CFA5C8" },
    ["@lsp.type.variable"] = { fg = "#9D88A5" },
    ["@lsp.type.interface"] = { fg = "#C190B8" },
    ["@lsp.type.variable.lua"] = { fg = "#E1C1D6" },
    ["@lsp.type.property.lua"] = { fg = "#E1C1D6" },
    ["@lsp.type.method.lua"] = { fg = "#CFA5C8" },
    ["@lsp.type.class.typescript"] = { fg = "#CFA5C8" },
    ["@lsp.type.enum.typescript"] = { fg = "#CFA5C8" },
    ["@lsp.type.interface.typescript"] = { fg = "#CFA5C8" },
    ["@lsp.type.namespace.typescript"] = { fg = "#BC9CF7" },
    ["@lsp.type.parameter.typescript"] = { fg = "#CFA5C8" },
    ["@lsp.type.property.typescript"] = { fg = "#CFA5C8" },
    ["@lsp.type.variable.typescript"] = { fg = "#9D88A5" },
    ["@lsp.type.class.python"] = { fg = "#78A0F7" },
    ["@lsp.type.decorator.python"] = { fg = "#BC9CF7" },
    ["@lsp.type.function.python"] = { fg = "#CFA5C8" },
    ["@lsp.type.method.python"] = { fg = "#78A0F7" },
    ["@lsp.type.parameter.python"] = { fg = "#CFA5C8" },
    ["@lsp.type.variable.python"] = { fg = "#9D88A5" },
    ["@type.typescript"] = { fg = "#CFA5C8" },
    ["@type.javascript"] = { fg = "#CFA5C8" },
    ["@function.typescript"] = { fg = "#CFA5C8" },
    ["@function.javascript"] = { fg = "#CFA5C8" },
    ["@string.typescript"] = { fg = "#E1C1D6" },
    ["@string.javascript"] = { fg = "#E1C1D6" },
    ["@markup.heading.1.markdown"] = { fg = "#CFA5C8", bold = true },
    ["NormalFloat"] = { fg = "#E1C1D6", bg = "#232334" },
    ["FloatBorder"] = { fg = "#9D88A5", bg = "#232334" },
    ["ColorColumn"] = { bg = "#232334" },
    ["Cursor"] = { fg = "#1B1B27", bg = "#CFA5C8" },
    ["CursorLine"] = { bg = "#232334" },
    ["CursorLineNr"] = { fg = "#CFA5C8", bg = "#232334" },
    ["LineNr"] = { fg = "#6E7296" },
    ["SignColumn"] = { fg = "#6E7296", bg = "#1B1B27" },
    ["VertSplit"] = { fg = "#2F3246" },
    ["EndOfBuffer"] = { fg = "#2F3246" },
    ["Folded"] = { fg = "#C190B8", bg = "#232334" },
    ["FoldColumn"] = { fg = "#6E7296", bg = "#1B1B27" },
    ["StatusLine"] = { fg = "#CFA5C8", bg = "#2F3246" },
    ["StatusLineNC"] = { fg = "#6E7296", bg = "#232334" },
    ["Pmenu"] = { fg = "#CFA5C8", bg = "#232334" },
    ["PmenuSel"] = { fg = "#1B1B27", bg = "#CFA5C8" },
    ["PmenuSbar"] = { bg = "#2F3246" },
    ["PmenuThumb"] = { bg = "#9D88A5" },
    ["Search"] = { fg = "#1B1B27", bg = "#E1C1D6" },
    ["IncSearch"] = { fg = "#1B1B27", bg = "#CFA5C8" },
    ["CurSearch"] = { fg = "#1B1B27", bg = "#CFA5C8" },
    ["Visual"] = { bg = "#3A3D55" },
    ["VisualNOS"] = { bg = "#3A3D55" },
    ["DiffAdd"] = { fg = "#9DCE69", bg = "#232334" },
    ["DiffChange"] = { fg = "#FF9E66", bg = "#232334" },
    ["Normal"] = { fg = "#E1C1D6", bg = "#1B1B27" },
    ["DiffText"] = { fg = "#1B1B27", bg = "#FF9E66" },
    ["Comment"] = { fg = "#6E7296", italic = true },
    ["Constant"] = { fg = "#FF9E66" },
    ["String"] = { fg = "#72DACA" },
    ["Character"] = { fg = "#72DACA" },
    ["Number"] = { fg = "#FF9E66" },
    ["Boolean"] = { fg = "#FF9E66" },
    ["Float"] = { fg = "#FF9E66" },
    ["Identifier"] = { fg = "#E1C1D6" },
    ["Function"] = { fg = "#CFA5C8" },
    ["Statement"] = { fg = "#C190B8" },
    ["Conditional"] = { fg = "#C190B8" },
    ["Repeat"] = { fg = "#C190B8" },
    ["Label"] = { fg = "#C190B8" },
    ["Operator"] = { fg = "#E0E0F0" },
    ["@operator"] = { fg = "#E0E0F0" },
    ["Keyword"] = { fg = "#C190B8" },
    ["Exception"] = { fg = "#F7788F" },
    ["PreProc"] = { fg = "#BC9CF7" },
    ["@field.yaml"] = { fg = "#CFA5C8" },
    ["@string.special.key.json"] = { fg = "#CFA5C8" },
    ["@property.json"] = { fg = "#CFA5C8" },
    ["@markup.heading.6.markdown"] = { fg = "#CFA5C8", bold = true },
    ["@markup.heading.5.markdown"] = { fg = "#CFA5C8", bold = true },
    ["@markup.heading.4.markdown"] = { fg = "#CFA5C8", bold = true },
    ["@markup.heading.3.markdown"] = { fg = "#CFA5C8", bold = true },
    ["@markup.heading.2.markdown"] = { fg = "#CFA5C8", bold = true },
    ["DiffDelete"] = { fg = "#F7788F", bg = "#232334" },
  }
  return highlights
end

return M
